[package]
name = "renderer"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
anyhow.workspace = true

utils.workspace = true
platform.workspace = true
resource_manager.workspace = true
world.workspace = true

ash.workspace = true
ash-window.workspace = true
raw-window-handle.workspace = true
glam.workspace = true

[build-dependencies]
build.workspace = true
