[package]
name = "renderer"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
anyhow.workspace = true

platform.workspace = true

ash.workspace = true
ash-window.workspace = true
winit.workspace = true
glam.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(validation)"] }
