#![allow(
    clippy::missing_errors_doc,
    reason = "command recording errors are backend-dependent and use the crate Error contract"
)]

use crate::{
    Backend, Color, Extent3d, FilterMode, ImageAspects, ImageState, IndexFormat, LoadOp, Origin3d,
    PipelineStages, Rect, Result, StoreOp, Viewport,
};

/// Buffer-to-buffer copy region.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct BufferCopy {
    /// Source byte offset.
    pub src_offset: u64,
    /// Destination byte offset.
    pub dst_offset: u64,
    /// Number of bytes copied.
    pub size: u64,
}

/// Buffer-to-image copy region.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BufferImageCopy {
    /// Source byte offset.
    pub buffer_offset: u64,
    /// First destination mip level.
    pub mip_level: u32,
    /// First destination array layer.
    pub base_array_layer: u32,
    /// Destination layer count.
    pub array_layer_count: u32,
    /// Destination image extent.
    pub extent: Extent3d,
    /// Copied image aspects.
    pub aspects: ImageAspects,
}

/// Image-to-image copy region.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ImageCopy {
    /// Source mip level.
    pub src_mip_level: u32,
    /// First source array layer.
    pub src_base_array_layer: u32,
    /// Destination mip level.
    pub dst_mip_level: u32,
    /// First destination array layer.
    pub dst_base_array_layer: u32,
    /// Number of copied array layers.
    pub array_layer_count: u32,
    /// Source texel origin.
    pub src_origin: Origin3d,
    /// Destination texel origin.
    pub dst_origin: Origin3d,
    /// Copied image extent.
    pub extent: Extent3d,
    /// Copied image aspects.
    pub aspects: ImageAspects,
}

/// Image blit region.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ImageBlit {
    /// Source mip level.
    pub src_mip_level: u32,
    /// Destination mip level.
    pub dst_mip_level: u32,
    /// Source dimensions.
    pub src_extent: Extent3d,
    /// Destination dimensions.
    pub dst_extent: Extent3d,
}

/// Image transition generated by the render graph or upload path.
pub struct ImageBarrier<'a, B: Backend> {
    /// Transitioned image.
    pub image: &'a B::Image,
    /// State before the transition.
    pub old_state: ImageState,
    /// State after the transition.
    pub new_state: ImageState,
    /// Selected image aspects.
    pub aspects: ImageAspects,
    /// First mip level.
    pub base_mip_level: u32,
    /// Mip level count.
    pub mip_level_count: u32,
    /// First array layer.
    pub base_array_layer: u32,
    /// Array layer count.
    pub array_layer_count: u32,
}

/// A group of resource transitions.
pub struct DependencyInfo<'a, B: Backend> {
    /// Image transitions.
    pub image_barriers: &'a [ImageBarrier<'a, B>],
}

/// Color attachment used by a dynamic rendering pass.
pub struct ColorAttachment<'a, B: Backend> {
    /// Render target view.
    pub view: &'a B::ImageView,
    /// Optional multisample resolve target.
    pub resolve: Option<&'a B::ImageView>,
    /// Initial contents operation.
    pub load: LoadOp<Color>,
    /// Final contents operation.
    pub store: StoreOp,
}

/// Depth/stencil attachment used by a dynamic rendering pass.
pub struct DepthAttachment<'a, B: Backend> {
    /// Depth target view.
    pub view: &'a B::ImageView,
    /// Initial depth operation.
    pub depth_load: LoadOp<f32>,
    /// Final depth operation.
    pub depth_store: StoreOp,
    /// Initial stencil operation.
    pub stencil_load: LoadOp<u32>,
    /// Final stencil operation.
    pub stencil_store: StoreOp,
}

/// Dynamic rendering pass description.
pub struct RenderingInfo<'a, B: Backend> {
    /// Debug label.
    pub label: &'a str,
    /// Render target dimensions.
    pub extent: Extent3d,
    /// Color attachments.
    pub color_attachments: &'a [ColorAttachment<'a, B>],
    /// Optional depth/stencil attachment.
    pub depth_attachment: Option<DepthAttachment<'a, B>>,
}

/// Timeline semaphore and target value used by a submission.
pub struct TimelinePoint<'a, B: Backend> {
    /// Timeline semaphore.
    pub semaphore: &'a B::TimelineSemaphore,
    /// Counter value waited for or signaled.
    pub value: u64,
    /// Pipeline stages blocked by a wait.
    pub stages: PipelineStages,
}

/// Backend command buffer recording interface.
pub trait CommandBuffer<B: Backend> {
    /// Begins command recording.
    fn begin(&mut self, label: &str, one_time_submit: bool) -> Result<()>;
    /// Ends command recording.
    fn end(&mut self) -> Result<()>;
    /// Begins a rendering pass.
    fn begin_rendering(&mut self, info: &RenderingInfo<'_, B>) -> Result<()>;
    /// Ends the active rendering pass.
    fn end_rendering(&mut self) -> Result<()>;
    /// Sets the active viewport.
    fn set_viewport(&mut self, viewport: Viewport);
    /// Sets the active scissor rectangle.
    fn set_scissor(&mut self, scissor: Rect);
    /// Binds a graphics pipeline.
    fn bind_graphics_pipeline(&mut self, pipeline: &B::GraphicsPipeline);
    /// Binds resource groups to a pipeline layout.
    fn bind_groups(
        &mut self,
        layout: &B::PipelineLayout,
        first_group: u32,
        groups: &[&B::BindGroup],
    );
    /// Binds one vertex buffer.
    fn bind_vertex_buffer(&mut self, slot: u32, buffer: &B::Buffer, offset: u64);
    /// Binds an index buffer.
    fn bind_index_buffer(&mut self, buffer: &B::Buffer, offset: u64, format: IndexFormat);
    /// Records an indexed draw.
    fn draw_indexed(
        &mut self,
        index_count: u32,
        instance_count: u32,
        first_index: u32,
        vertex_offset: i32,
        first_instance: u32,
    );
    /// Copies buffer regions.
    fn copy_buffer(&mut self, src: &B::Buffer, dst: &B::Buffer, regions: &[BufferCopy]);
    /// Copies a buffer into an image.
    fn copy_buffer_to_image(
        &mut self,
        src: &B::Buffer,
        dst: &B::Image,
        regions: &[BufferImageCopy],
    );
    /// Copies image regions without filtering.
    fn copy_image(&mut self, src: &B::Image, dst: &B::Image, regions: &[ImageCopy]);
    /// Blits between image mip levels.
    fn blit_image(
        &mut self,
        src: &B::Image,
        dst: &B::Image,
        regions: &[ImageBlit],
        filter: FilterMode,
    ) -> Result<()>;
    /// Applies resource transitions.
    fn barrier(&mut self, dependency: &DependencyInfo<'_, B>);
}
