use crate::{
    AddressMode, Backend, BindingType, BufferUsages, CompareOp, CullMode, Extent3d, FilterMode,
    Format, FrontFace, ImageAspects, ImageUsages, ImageViewType, MemoryDomain, PrimitiveTopology,
    Result, SampleCount, ShaderStage, ShaderStages, VertexBufferLayout,
};

/// Backend buffer with host-write behavior when its memory domain permits it.
pub trait Buffer: Clone + Send + Sync + 'static {
    /// Writes bytes into this buffer's host-visible memory.
    ///
    /// # Errors
    ///
    /// Returns an error when the buffer is not host-visible or the requested
    /// range falls outside its allocation.
    fn write(&self, offset: u64, data: &[u8]) -> Result<()>;
}

/// Buffer allocation description.
#[derive(Clone, Copy, Debug)]
pub struct BufferDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Buffer size in bytes.
    pub size: u64,
    /// Permitted buffer uses.
    pub usage: BufferUsages,
    /// Preferred host/GPU access pattern.
    pub memory: MemoryDomain,
}

/// Image allocation description.
#[derive(Clone, Copy, Debug)]
pub struct ImageDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Image dimensions.
    pub extent: Extent3d,
    /// Texel format.
    pub format: Format,
    /// Permitted image uses.
    pub usage: ImageUsages,
    /// Mip level count.
    pub mip_levels: u32,
    /// Array layer count.
    pub array_layers: u32,
    /// Multisampling count.
    pub samples: SampleCount,
}

/// Image-view description.
#[derive(Clone, Copy, Debug)]
pub struct ImageViewDesc<'a, B: Backend> {
    /// Debug label.
    pub label: &'a str,
    /// Image being viewed.
    pub image: &'a B::Image,
    /// View dimensionality.
    pub view_type: ImageViewType,
    /// Selected image aspects.
    pub aspects: ImageAspects,
    /// First visible mip level.
    pub base_mip_level: u32,
    /// Visible mip level count.
    pub mip_level_count: u32,
    /// First visible array layer.
    pub base_array_layer: u32,
    /// Visible array layer count.
    pub array_layer_count: u32,
}

/// Texture sampler description.
#[derive(Clone, Copy, Debug)]
pub struct SamplerDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Magnification filtering.
    pub mag_filter: FilterMode,
    /// Minification filtering.
    pub min_filter: FilterMode,
    /// Mipmap filtering.
    pub mip_filter: FilterMode,
    /// Horizontal address mode.
    pub address_u: AddressMode,
    /// Vertical address mode.
    pub address_v: AddressMode,
    /// Depth address mode.
    pub address_w: AddressMode,
    /// Maximum anisotropy, where one disables anisotropic filtering.
    pub max_anisotropy: u16,
    /// Minimum mip level.
    pub lod_min: f32,
    /// Maximum mip level.
    pub lod_max: f32,
}

/// Shader source accepted by graphics backends.
#[derive(Clone, Copy, Debug)]
pub enum ShaderSource<'a> {
    /// SPIR-V words generated by the engine shader build.
    SpirV(&'a [u32]),
    /// Metal Shading Language source for native Metal specialization.
    Msl(&'a str),
}

/// Shader module description.
#[derive(Clone, Copy, Debug)]
pub struct ShaderDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Programmable stage.
    pub stage: ShaderStage,
    /// Entry-point function name.
    pub entry: &'a str,
    /// Shader source.
    pub source: ShaderSource<'a>,
}

/// One resource binding in a layout.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct BindGroupLayoutEntry {
    /// Binding index.
    pub binding: u32,
    /// Bound resource type.
    pub ty: BindingType,
    /// Shader stages allowed to access the binding.
    pub visibility: ShaderStages,
}

/// Bind-group layout description.
#[derive(Clone, Copy, Debug)]
pub struct BindGroupLayoutDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Binding declarations.
    pub entries: &'a [BindGroupLayoutEntry],
}

/// Resource written into a bind group.
pub enum BindingResource<'a, B: Backend> {
    /// Byte range of a buffer.
    Buffer {
        /// Buffer resource.
        buffer: &'a B::Buffer,
        /// Byte offset.
        offset: u64,
        /// Byte size.
        size: u64,
    },
    /// Sampled image view and sampler.
    SampledImage {
        /// Image view.
        view: &'a B::ImageView,
        /// Texture sampler.
        sampler: &'a B::Sampler,
    },
    /// Storage image view.
    StorageImage(&'a B::ImageView),
}

/// One bind-group resource entry.
pub struct BindGroupEntry<'a, B: Backend> {
    /// Binding index from the layout.
    pub binding: u32,
    /// Bound resource.
    pub resource: BindingResource<'a, B>,
}

/// Bind-group creation description.
pub struct BindGroupDesc<'a, B: Backend> {
    /// Debug label.
    pub label: &'a str,
    /// Layout implemented by the bind group.
    pub layout: &'a B::BindGroupLayout,
    /// Resources written into the group.
    pub entries: &'a [BindGroupEntry<'a, B>],
}

/// Pipeline-layout description.
pub struct PipelineLayoutDesc<'a, B: Backend> {
    /// Debug label.
    pub label: &'a str,
    /// Bind-group layouts ordered by set/group index.
    pub bind_group_layouts: &'a [&'a B::BindGroupLayout],
}

/// Rasterization state.
#[derive(Clone, Copy, Debug, Default)]
pub struct RasterState {
    /// Primitive topology.
    pub topology: PrimitiveTopology,
    /// Front-face winding.
    pub front_face: FrontFace,
    /// Face culling mode.
    pub cull_mode: CullMode,
}

/// Depth attachment pipeline state.
#[derive(Clone, Copy, Debug)]
pub struct DepthState {
    /// Depth texture format.
    pub format: Format,
    /// Whether fragment depth is written.
    pub write_enabled: bool,
    /// Depth comparison operation.
    pub compare: CompareOp,
}

/// Graphics pipeline description.
pub struct GraphicsPipelineDesc<'a, B: Backend> {
    /// Debug label.
    pub label: &'a str,
    /// Pipeline resource layout.
    pub layout: &'a B::PipelineLayout,
    /// Vertex shader.
    pub vertex: &'a B::Shader,
    /// Fragment shader.
    pub fragment: &'a B::Shader,
    /// Vertex-buffer layouts.
    pub vertex_buffers: &'a [VertexBufferLayout<'a>],
    /// Rasterization state.
    pub raster: RasterState,
    /// Color attachment formats.
    pub color_formats: &'a [Format],
    /// Optional depth state.
    pub depth: Option<DepthState>,
    /// Multisampling count.
    pub samples: SampleCount,
}
