use crate::{
    AddressMode, Backend, BindingType, BufferUsages, CompareOp, CullMode, Extent3d, FilterMode,
    Format, FrontFace, ImageAspects, ImageUsages, ImageViewType, MemoryDomain, PrimitiveTopology,
    Result, SampleCount, ShaderStage, ShaderStages, VertexBufferLayout,
};

/// Backend buffer with host-write behavior when its memory domain permits it.
pub trait Buffer: Clone + Send + Sync + 'static {
    /// Writes bytes into this buffer's host-visible memory.
    ///
    /// # Errors
    ///
    /// Returns an error when the buffer is not host-visible or the requested
    /// range falls outside its allocation.
    ///
    /// Callers must prevent concurrent writes to overlapping ranges of the
    /// same buffer, including writes made through cloned buffer handles.
    /// Implementations are not required to serialize such writes.
    fn write(&self, offset: u64, data: &[u8]) -> Result<()>;
}

/// Buffer allocation description.
#[derive(Clone, Copy, Debug)]
pub struct BufferDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Buffer size in bytes.
    pub size: u64,
    /// Permitted buffer uses.
    pub usage: BufferUsages,
    /// Preferred host/GPU access pattern.
    pub memory: MemoryDomain,
}

/// Image allocation description.
#[derive(Clone, Copy, Debug)]
pub struct ImageDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Image dimensions. For a two-dimensional array image, `depth` must be
    /// one; array layers are specified only by [`Self::array_layers`].
    pub extent: Extent3d,
    /// Texel format.
    pub format: Format,
    /// Permitted image uses.
    pub usage: ImageUsages,
    /// Mip level count.
    pub mip_levels: u32,
    /// Array layer count.
    pub array_layers: u32,
    /// Multisampling count.
    pub samples: SampleCount,
}

/// Image-view description.
#[derive(Clone, Copy)]
pub struct ImageViewDesc<'a, B: Backend> {
    /// Debug label.
    pub label: &'a str,
    /// Image being viewed.
    pub image: &'a B::Image,
    /// View dimensionality.
    pub view_type: ImageViewType,
    /// Selected image aspects.
    pub aspects: ImageAspects,
    /// First visible mip level.
    pub base_mip_level: u32,
    /// Visible mip level count.
    pub mip_level_count: u32,
    /// First visible array layer.
    pub base_array_layer: u32,
    /// Visible array layer count.
    pub array_layer_count: u32,
}

impl<B: Backend> std::fmt::Debug for ImageViewDesc<'_, B> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ImageViewDesc")
            .field("label", &self.label)
            .field("view_type", &self.view_type)
            .field("aspects", &self.aspects)
            .field("base_mip_level", &self.base_mip_level)
            .field("mip_level_count", &self.mip_level_count)
            .field("base_array_layer", &self.base_array_layer)
            .field("array_layer_count", &self.array_layer_count)
            .finish_non_exhaustive()
    }
}

/// Texture sampler description.
#[derive(Clone, Copy, Debug)]
pub struct SamplerDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Magnification filtering.
    pub mag_filter: FilterMode,
    /// Minification filtering.
    pub min_filter: FilterMode,
    /// Mipmap filtering.
    pub mip_filter: FilterMode,
    /// Horizontal address mode.
    pub address_u: AddressMode,
    /// Vertical address mode.
    pub address_v: AddressMode,
    /// Depth address mode.
    pub address_w: AddressMode,
    /// Maximum anisotropy, where one disables anisotropic filtering.
    pub max_anisotropy: u16,
    /// Minimum mip level.
    pub lod_min: f32,
    /// Maximum mip level.
    pub lod_max: f32,
}

/// Shader source accepted by graphics backends.
#[derive(Clone, Copy, Debug)]
pub enum ShaderSource<'a> {
    /// SPIR-V words generated by the engine shader build.
    SpirV(&'a [u32]),
    /// Metal Shading Language source for native Metal specialization.
    Msl(&'a str),
}

/// Shader module description.
#[derive(Clone, Copy, Debug)]
pub struct ShaderDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Programmable stage.
    pub stage: ShaderStage,
    /// Entry-point function name.
    pub entry: &'a str,
    /// Shader source.
    pub source: ShaderSource<'a>,
}

/// One resource binding in a layout.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct BindGroupLayoutEntry {
    /// Binding index.
    pub binding: u32,
    /// Bound resource type.
    pub ty: BindingType,
    /// Shader stages allowed to access the binding.
    pub visibility: ShaderStages,
}

/// Bind-group layout description.
#[derive(Clone, Copy, Debug)]
pub struct BindGroupLayoutDesc<'a> {
    /// Debug label.
    pub label: &'a str,
    /// Binding declarations.
    pub entries: &'a [BindGroupLayoutEntry],
}

/// Resource written into a bind group.
pub enum BindingResource<'a, B: Backend> {
    /// Byte range of a buffer.
    Buffer {
        /// Buffer resource.
        buffer: &'a B::Buffer,
        /// Byte offset.
        offset: u64,
        /// Byte size.
        size: u64,
    },
    /// Sampled image view and sampler.
    SampledImage {
        /// Image view.
        view: &'a B::ImageView,
        /// Texture sampler.
        sampler: &'a B::Sampler,
    },
    /// Storage image view.
    StorageImage(&'a B::ImageView),
}

impl<B: Backend> Copy for BindingResource<'_, B> {}

impl<B: Backend> Clone for BindingResource<'_, B> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<B: Backend> std::fmt::Debug for BindingResource<'_, B> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Buffer { offset, size, .. } => formatter
                .debug_struct("BindingResource::Buffer")
                .field("offset", offset)
                .field("size", size)
                .finish(),
            Self::SampledImage { .. } => formatter.write_str("BindingResource::SampledImage"),
            Self::StorageImage(_) => formatter.write_str("BindingResource::StorageImage"),
        }
    }
}

/// One bind-group resource entry.
pub struct BindGroupEntry<'a, B: Backend> {
    /// Binding index from the layout.
    pub binding: u32,
    /// Bound resource.
    pub resource: BindingResource<'a, B>,
}

impl<B: Backend> Copy for BindGroupEntry<'_, B> {}

impl<B: Backend> Clone for BindGroupEntry<'_, B> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<B: Backend> std::fmt::Debug for BindGroupEntry<'_, B> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("BindGroupEntry")
            .field("binding", &self.binding)
            .field("resource", &self.resource)
            .finish()
    }
}

/// Bind-group creation description.
pub struct BindGroupDesc<'a, B: Backend> {
    /// Debug label.
    pub label: &'a str,
    /// Layout implemented by the bind group.
    pub layout: &'a B::BindGroupLayout,
    /// Resources written into the group.
    pub entries: &'a [BindGroupEntry<'a, B>],
}

impl<B: Backend> Copy for BindGroupDesc<'_, B> {}

impl<B: Backend> Clone for BindGroupDesc<'_, B> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<B: Backend> std::fmt::Debug for BindGroupDesc<'_, B> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("BindGroupDesc")
            .field("label", &self.label)
            .field("entries", &self.entries)
            .finish_non_exhaustive()
    }
}

/// Pipeline-layout description.
pub struct PipelineLayoutDesc<'a, B: Backend> {
    /// Debug label.
    pub label: &'a str,
    /// Bind-group layouts ordered by set/group index.
    pub bind_group_layouts: &'a [&'a B::BindGroupLayout],
}

impl<B: Backend> Copy for PipelineLayoutDesc<'_, B> {}

impl<B: Backend> Clone for PipelineLayoutDesc<'_, B> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<B: Backend> std::fmt::Debug for PipelineLayoutDesc<'_, B> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PipelineLayoutDesc")
            .field("label", &self.label)
            .field("bind_group_layout_count", &self.bind_group_layouts.len())
            .finish_non_exhaustive()
    }
}

/// Rasterization state.
#[derive(Clone, Copy, Debug, Default)]
pub struct RasterState {
    /// Primitive topology.
    pub topology: PrimitiveTopology,
    /// Front-face winding.
    pub front_face: FrontFace,
    /// Face culling mode.
    pub cull_mode: CullMode,
}

/// Depth attachment pipeline state.
#[derive(Clone, Copy, Debug)]
pub struct DepthState {
    /// Depth texture format.
    pub format: Format,
    /// Whether fragment depth is written.
    pub write_enabled: bool,
    /// Depth comparison operation.
    pub compare: CompareOp,
}

/// Graphics pipeline description.
pub struct GraphicsPipelineDesc<'a, B: Backend> {
    /// Debug label.
    pub label: &'a str,
    /// Pipeline resource layout.
    pub layout: &'a B::PipelineLayout,
    /// Vertex shader.
    pub vertex: &'a B::Shader,
    /// Optional fragment shader. Depth-only passes leave this unset.
    pub fragment: Option<&'a B::Shader>,
    /// Vertex-buffer layouts.
    pub vertex_buffers: &'a [VertexBufferLayout<'a>],
    /// Rasterization state.
    pub raster: RasterState,
    /// Color attachment formats.
    pub color_formats: &'a [Format],
    /// Optional depth state.
    pub depth: Option<DepthState>,
    /// Multisampling count.
    pub samples: SampleCount,
}

impl<B: Backend> Copy for GraphicsPipelineDesc<'_, B> {}

impl<B: Backend> Clone for GraphicsPipelineDesc<'_, B> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<B: Backend> std::fmt::Debug for GraphicsPipelineDesc<'_, B> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("GraphicsPipelineDesc")
            .field("label", &self.label)
            .field("has_fragment_shader", &self.fragment.is_some())
            .field("vertex_buffers", &self.vertex_buffers)
            .field("raster", &self.raster)
            .field("color_formats", &self.color_formats)
            .field("depth", &self.depth)
            .field("samples", &self.samples)
            .finish_non_exhaustive()
    }
}
