[package]
name = "dirk_run"
default-run = "dirk_run"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tracing.workspace = true
tracing-log.workspace = true
anyhow.workspace = true

dirk_engine.workspace = true

[lints]
workspace = true
