[package]
name = "dirk_platform"
description = "DirkEngine platform API"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

homepage.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
winit.workspace = true

dirk_events.workspace = true

glam.workspace = true

[build-dependencies]
dirk_build.workspace = true

[lints]
workspace = true
