[workspace]
resolver = "3"
members = ["Engine/Source/engine","Engine/Source/logging", "Engine/Source/platform", "Engine/Source/renderer","Engine/Source/run"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/PiquelChips/DirkEngine"
rust-version = "1.94.0"
version = "0.1.0"

[workspace.dependencies]
# Basic stuff
log  = { version = "0.4", features = ["std"] }
time = { version = "0.3", features = ["formatting"] }

thiserror = "2"
anyhow = "1"
# Engine modules
logging = { path = "Engine/Source/logging" }
engine = { path = "Engine/Source/engine" }
platform = { path = "Engine/Source/platform" }
# TODO: find a way to only enable this in debug builds
renderer = { path = "Engine/Source/renderer" }

# Main Engine Dependencies
winit = "0.31.0-beta.2"
ash = { version = "0.38", features = ["loaded"] }
ash-window = "0.13"
glam = "0.32"
