[workspace]
resolver = "3"
members = [
    "crates/*",
    "shaders"
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/DirkEngine/DirkEngine"
rust-version = "1.94.0"
version = "0.1.0-alpha-2"

homepage = "https://piquel.fr" # TODO: should piquel.fr/dirk of dirkengine.fr
authors = ["Piquel Chips <contact@piquel.fr>"]
documentation = "https://docs.rs/dirkengine/latest/dirkengine"
keywords = ["game", "engine", "gamedev", "graphics", "vulkan"]
categories = ["game-engines", "graphics", "rendering", "vulkan"]

[workspace.dependencies]
# Basic stuff
time = { version = "0.3", features = ["formatting", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["registry", "std"] }
tracing-log = "0.2"
parking_lot = "0.12"
tempfile = "3"
slotmap = "1"

thiserror = "2"
anyhow = "1"
cargo_metadata = "0.23"

# Engine modules
dirkengine    = { version = "0.1.0-alpha-2", path = "crates/dirk_engine" }

dirk_build    = { version = "0.1.0-alpha-2", path = "crates/dirk_build" }
dirk_utils    = { version = "0.1.0-alpha-2", path = "crates/dirk_utils" }
dirk_logging  = { version = "0.1.0-alpha-2", path = "crates/dirk_logging" }
dirk_events   = { version = "0.1.0-alpha-2", path = "crates/dirk_events" }
dirk_proc     = { version = "0.1.0-alpha-2", path = "crates/dirk_proc" }
dirk_platform = { version = "0.1.0-alpha-2", path = "crates/dirk_platform" }
dirk_renderer = { version = "0.1.0-alpha-2", path = "crates/dirk_renderer" }
dirk_assets   = { version = "0.1.0-alpha-2", path = "crates/dirk_assets" }
dirk_world    = { version = "0.1.0-alpha-2", path = "crates/dirk_world" }
dirk_universe = { version = "0.1.0-alpha-2", path = "crates/dirk_universe" }

dirk_shaders  = { version = "0.1.0-alpha-2", path = "shaders" }

# Main Engine Dependencies
winit = "0.31.0-beta.2"
ash = { version = "0.38", features = ["loaded"] }
ash-window = "0.13"
raw-window-handle = "0.6"
glam = "0.32"
gltf = "1"
shaderc = "0.10"
gpu-allocator = { version = "0.28", default-features = false, features = ["std", "vulkan"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Macro dependencies
syn = { version = "2", features = ["full"] }
quote = "1"
pastey = "0.2"
proc-macro2 = "1"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
pedantic = "warn"
unwrap_used = "warn"
