[package]
name = "engine"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true

logging.workspace = true
utils.workspace = true
platform.workspace = true
renderer.workspace = true
world.workspace = true
