[package]
name = "engine"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
derive-getters.workspace = true
tracing.workspace = true

logging.workspace = true
utils.workspace = true
events.workspace = true
platform.workspace = true
renderer.workspace = true
world.workspace = true
resource_manager.workspace = true
assets.workspace = true

glam.workspace = true

[build-dependencies]
build.workspace = true

[lints]
workspace = true
