[package]
name = "dirk_renderer"
description = "DirkEngine's renderer"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

homepage.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
pastey.workspace = true

dirk_utils.workspace = true
dirk_engine.workspace = true
dirk_input.workspace = true
dirk_rhi.workspace = true
dirk_rhi_vulkan.workspace = true
dirk_platform.workspace = true
dirk_player.workspace = true
dirk_universe.workspace = true
dirk_world.workspace = true
dirk_shaders.workspace = true
dirk_events.workspace = true
dirk_assets.workspace = true

ash.workspace = true
ash-window.workspace = true
raw-window-handle.workspace = true
glam.workspace = true
gpu-allocator.workspace = true
gltf.workspace = true
slotmap.workspace = true
egui = { workspace = true, optional = true }
egui-ash-renderer = { workspace = true, optional = true }

[build-dependencies]
cargo-gpu-install.workspace = true
anyhow.workspace = true
rspirv-reflect.workspace = true
quote.workspace = true
proc-macro2.workspace = true

dirk_build.workspace = true

[features]
default = []

editor = [
    "dirk_engine/editor",
    "dirk_input/egui",
    "dep:egui",
    "dep:egui-ash-renderer",
]

[lints.rust]
missing_docs = "warn"
unsafe_code = "allow"

[lints.clippy]
pedantic = "warn"
unwrap_used = "warn"
