[package]
name = "platform"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
winit.workspace = true

events.workspace = true

glam.workspace = true

[build-dependencies]
build.workspace = true

[lints]
workspace = true
