[package]
name = "dirk_utils"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
thiserror.workspace = true
glam.workspace = true

[build-dependencies]
dirk_build.workspace = true

[lints]
workspace = true
