use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{DeriveInput, FnArg, ItemTrait, LitStr, Pat, TraitItem, TypeParamBound};

// this function is long because of the quote & the documentation.
#[allow(clippy::too_many_lines)]
pub fn generate_system_code(trait_def: &ItemTrait) -> syn::Result<TokenStream> {
    if !trait_def.supertraits.iter().any(|s| match s {
        TypeParamBound::Trait(t) => t.path.segments.last().is_some_and(|s| s.ident == "System"),
        _ => false,
    }) {
        return Err(syn::Error::new(
            trait_def.ident.span(),
            "this trait must have the `System` trait in its param bounds",
        ));
    }

    let trait_name = &trait_def.ident;
    let any_name = format_ident!("Any{trait_name}");
    let storage = format_ident!("{trait_name}Storage");

    let trait_name_str = trait_name.to_string();
    let any_name_str = any_name.to_string();
    let storage_str = storage.to_string();

    let fns: Vec<_> = trait_def
        .items
        .iter()
        .filter_map(|item| {
            if let TraitItem::Fn(m) = item {
                Some(m)
            } else {
                None
            }
        })
        .collect();

    let any_sigs = fns.iter().map(|m| {
        let s = &m.sig;
        quote!(#s;)
    });

    let blanket_methods = fns.iter().map(|m| {
        let sig = &m.sig;
        let name = &m.sig.ident;
        let args = get_arg_names_from_sig(&m.sig);
        quote! {
            #sig { T::#name(#(#args),*) }
        }
    });

    // Doc strings for the Any* trait.
    let any_doc_main = format!(
        "Object-safe mirror of [`{trait_name_str}`], generated by the [`system_trait`](macros::system_trait) macro."
    );
    let any_doc_detail = format!(
        "This trait is automatically implemented for every `T: {trait_name_str}` via a blanket \
         implementation, so you never need to implement it manually. Its sole purpose is to allow \
         heterogeneous collections of `{trait_name_str}` implementors to be stored behind \
         `Box<dyn {any_name_str}>` inside [`{storage_str}`]."
    );
    let any_doc_manual = "Do **not** implement or call this trait directly.".to_string();

    // Doc strings for the Storage struct.
    let storage_doc_main =
        format!("Type-erased storage for any number of [`{trait_name_str}`] implementors.");
    let storage_doc_detail = format!(
        "Generated by the [`system_trait`](macros::system_trait) macro. Internally holds a \
         `Vec<Box<dyn {any_name_str}>>` so that concrete system types with different sizes and \
         layouts can coexist in the same collection."
    );

    // Doc strings for Storage methods.
    let new_doc = format!("Creates an empty [`{storage_str}`].");
    let insert_doc = format!(
        "Boxes `system` and appends it to this [`{storage_str}`].\n\n\
         The concrete type of `system` is erased after this call; it can only be \
         reached again through [`{storage_str}::iter`]."
    );
    let insert_any_doc = format!("Appends a Boxed `system` to this [`{storage_str}`].\n\n");
    let iter_doc = format!(
        "Returns an iterator over every system stored in this [`{storage_str}`], \
         as `Box<dyn {any_name_str}>`."
    );

    Ok(quote! {
        #trait_def

        #[doc = #any_doc_main]
        #[doc = ""]
        #[doc = #any_doc_detail]
        #[doc = ""]
        #[doc = #any_doc_manual]
        pub(crate) trait #any_name { #(#any_sigs)* }

        /// Blanket implementation of the object-safe mirror trait.
        ///
        /// Every method simply delegates to the corresponding method on the
        /// concrete type `T`, so there is no logic to maintain here — it is
        /// purely a forwarding layer that enables type erasure.
        impl<T: #trait_name> #any_name for T { #(#blanket_methods)* }

        #[doc = #storage_doc_main]
        #[doc = ""]
        #[doc = #storage_doc_detail]
        #[derive(Default)]
        pub(crate) struct #storage {
            systems: ::std::vec::Vec<Box<dyn #any_name>>
        }

        impl #storage {
            #[doc = #new_doc]
            pub fn new() -> Self { Self::default() }

            #[doc = #insert_doc]
            pub fn push(&mut self, system: impl #trait_name) {
                self.systems.push(Box::new(system));
            }

            #[doc = #insert_any_doc]
            pub fn push_any(&mut self, system: Box<dyn #any_name>) {
                self.systems.push(system);
            }

            #[doc = #iter_doc]
            pub fn iter(&self) -> std::slice::Iter<'_, Box<dyn #any_name>> {
                self.systems.iter()
            }
        }

        impl IntoIterator for #storage {
            type IntoIter = std::vec::IntoIter<Box<dyn #any_name>>;
            type Item = Box<dyn #any_name>;
            fn into_iter(self) -> Self::IntoIter {
                self.systems.into_iter()
            }
        }
    })
}

fn get_arg_names_from_sig(sig: &syn::Signature) -> Vec<TokenStream> {
    sig.inputs
        .iter()
        .map(|arg| match arg {
            FnArg::Typed(pt) => match &*pt.pat {
                Pat::Ident(id) => quote! { #id },
                &_ => todo!("implement other pattern types"),
            },
            FnArg::Receiver(_) => quote! {self},
        })
        .collect()
}

pub fn derive_system(input: &DeriveInput) -> TokenStream {
    let ident = &input.ident;

    let mut attr_name = None;
    for attr in &input.attrs {
        if attr.path().is_ident("system") {
            attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("name") {
                    let value = meta.value()?;
                    let s: LitStr = value.parse()?;
                    attr_name = Some(s.value());
                }
                Ok(())
            })
            .ok();
        }
    }

    let name = attr_name.unwrap_or_else(|| ident.to_string());

    quote! {
        impl System for #ident {
            fn name() -> &'static str {
                #name
            }
        }
    }
}
