[package]
name = "dirk_rhi"
description = "Backend-neutral render hardware interface for DirkEngine"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

homepage.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
raw-window-handle.workspace = true
thiserror.workspace = true

[lints]
workspace = true
