[package]
name = "world"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
glam.workspace = true
tracing.workspace = true

events.workspace = true
utils.workspace = true
platform.workspace = true
assets.workspace = true
universe.workspace = true

[lints]
workspace = true
