[package]
name = "dirk_events"
description = "Event system for DirkEngine"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
parking_lot.workspace = true

dirk_proc.workspace = true

tracing.workspace = true

[lints]
workspace = true
