[target.'cfg(target_os = "windows")']
rustflags = [ "--cfg", "platform_windows"]

[target.'cfg(target_os = "linux")']
rustflags = [ "--cfg", "platform_linux"]

[target.'cfg(target_os = "macos")']
rustflags = [ "--cfg", "platform_macos"]

[target.'cfg(target_os = "android")']
rustflags = [ "--cfg", "platform_android"]

[target.'cfg(target_os = "ios")']
rustflags = [ "--cfg", "platform_ios"]
