[package]
name = "dirk_engine"
description = "The API for the engine & its systems"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

homepage.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]

[lints]
workspace = true
