[package]
name = "dirk_engine"
description = "The API for the engine & its systems"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

homepage.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
piquel-log.workspace = true

dirk_threads.workspace = true
dirk_events.workspace = true
dirk_universe.workspace = true

[build-dependencies]
dirk_build.workspace = true

[features]
editor = []

[lints]
workspace = true
