[package]
name = "dirk_engine"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

dirk_logging.workspace = true
dirk_utils.workspace = true
dirk_events.workspace = true
dirk_platform.workspace = true
dirk_renderer.workspace = true
dirk_universe.workspace = true
dirk_world.workspace = true
dirk_assets.workspace = true

glam.workspace = true

[build-dependencies]
dirk_build.workspace = true

[lints]
workspace = true
