[package]
name = "dirk_shaders_gpu"
description = "DirkEngine's shaders"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

homepage.workspace = true
authors.workspace = true
documentation.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
spirv-std.workspace = true

[target.'cfg(target_arch = "spirv")'.dependencies]
glam = { version = ">=0.30.8", default-features = false, features = ["all-types", "libm"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_arch, values("spirv"))'] }
