name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'nix/**'
      - 'flake.nix'
      - 'flake.lock'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'nix/**'
      - 'flake.nix'
      - 'flake.lock'
      - 'README.md'

# Cancel any in-progress run on the same branch when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: cargo check (default features)
        run: cargo check --locked
      - name: cargo check (no default features)
        run: cargo check --locked --no-default-features
      - name: cargo check (all features)
        run: cargo check --locked --all-features

  build-and-test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: cargo build
        run: cargo build --locked
      - name: cargo test
        run: cargo test --locked
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: dirkengine-${{ matrix.os }}
          path: target/debug/run
